openapi: 3.1.0
info:
  title: Orakl Oncology public website CommonContent Folder API
  description: Orakl Oncology public website API
  version: 1.0.7
servers:
- url: /
  description: ''
security: []
tags:
- name: Folder
  description: Folders entity represent a directory on server with datetime and naming.
paths:
  /api/folders:
    get:
      operationId: api_folders_get_collection
      tags:
      - Folder
      responses:
        '200':
          description: Folder collection
          content:
            application/ld+json:
              schema:
                type: object
                description: Folder.jsonld-folder collection.
                allOf:
                - $ref: '#/components/schemas/HydraCollectionBaseSchema'
                - type: object
                  required:
                  - hydra:member
                  properties:
                    hydra:member:
                      type: array
                      items:
                        $ref: '#/components/schemas/Folder.jsonld-folder'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Folder-folder'
            application/x-www-form-urlencoded:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Folder.x-www-form-urlencoded-folder'
        '401':
          description: Invalid JWT Token
      summary: Retrieves the collection of Folder resources.
      description: Retrieves the collection of Folder resources.
      parameters:
      - name: page
        in: query
        description: The collection page number
        required: false
        deprecated: false
        schema:
          type: integer
          default: 1
        style: form
        explode: false
      - name: itemsPerPage
        in: query
        description: The number of items per page
        required: false
        deprecated: false
        schema:
          type: integer
          default: 15
          minimum: 0
          maximum: 50
        style: form
        explode: false
      - name: properties[]
        in: query
        description: 'Allows you to reduce the response to contain only the properties you need. If your desired property is nested, you can address it using nested arrays. Example: properties[]={propertyName}&properties[]={anotherPropertyName}&properties[{nestedPropertyParent}][]={nestedProperty}'
        required: false
        deprecated: false
        schema:
          type: array
          items:
            type: string
        style: form
        explode: false
      - name: order[position]
        in: query
        description: ''
        required: false
        deprecated: false
        schema:
          type: string
          default: asc
          enum:
          - asc
          - desc
        style: form
        explode: false
      - name: order[createdAt]
        in: query
        description: ''
        required: false
        deprecated: false
        schema:
          type: string
          default: asc
          enum:
          - asc
          - desc
        style: form
        explode: false
      - name: order[updatedAt]
        in: query
        description: ''
        required: false
        deprecated: false
        schema:
          type: string
          default: asc
          enum:
          - asc
          - desc
        style: form
        explode: false
      - name: parent.id
        in: query
        description: ''
        required: false
        deprecated: false
        schema:
          type: integer
        style: form
        explode: false
      - name: parent.id[]
        in: query
        description: ''
        required: false
        deprecated: false
        schema:
          type: array
          items:
            type: integer
        style: form
        explode: true
      - name: parent.folderName
        in: query
        description: ''
        required: false
        deprecated: false
        schema:
          type: string
        style: form
        explode: false
      - name: parent.folderName[]
        in: query
        description: ''
        required: false
        deprecated: false
        schema:
          type: array
          items:
            type: string
        style: form
        explode: true
      - name: folderName
        in: query
        description: ''
        required: false
        deprecated: false
        schema:
          type: string
        style: form
        explode: false
      - name: visible
        in: query
        description: ''
        required: false
        deprecated: false
        schema:
          type: boolean
        style: form
        explode: false
      - name: locked
        in: query
        description: ''
        required: false
        deprecated: false
        schema:
          type: boolean
        style: form
        explode: false
      - name: position[between]
        in: query
        description: ''
        required: false
        deprecated: false
        schema:
          type: string
        style: form
        explode: false
      - name: position[gt]
        in: query
        description: ''
        required: false
        deprecated: false
        schema:
          type: string
        style: form
        explode: false
      - name: position[gte]
        in: query
        description: ''
        required: false
        deprecated: false
        schema:
          type: string
        style: form
        explode: false
      - name: position[lt]
        in: query
        description: ''
        required: false
        deprecated: false
        schema:
          type: string
        style: form
        explode: false
      - name: position[lte]
        in: query
        description: ''
        required: false
        deprecated: false
        schema:
          type: string
        style: form
        explode: false
      - name: position
        in: query
        description: ''
        required: false
        deprecated: false
        schema:
          type: number
        style: form
        explode: false
      - name: position[]
        in: query
        description: ''
        required: false
        deprecated: false
        schema:
          type: array
          items:
            type: number
        style: form
        explode: true
      - name: _preview
        in: query
        description: Enables preview mode (requires a valid bearer JWT token)
        required: false
        deprecated: false
        schema:
          type: boolean
        style: form
        explode: false
        example: '1'
      security:
      - JWT: []
  /api/folders/{id}:
    get:
      operationId: api_folders_id_get
      tags:
      - Folder
      responses:
        '200':
          description: Folder resource
          content:
            application/ld+json:
              schema:
                $ref: '#/components/schemas/Folder.jsonld-folder'
            application/json:
              schema:
                $ref: '#/components/schemas/Folder-folder'
            application/x-www-form-urlencoded:
              schema:
                $ref: '#/components/schemas/Folder.x-www-form-urlencoded-folder'
        '404':
          description: Not found
          content:
            application/ld+json:
              schema:
                $ref: '#/components/schemas/Error.jsonld'
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Error'
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          links: {}
        '401':
          description: Invalid JWT Token
      summary: Retrieves a Folder resource.
      description: Retrieves a Folder resource.
      parameters:
      - name: id
        in: path
        description: Folder identifier
        required: true
        deprecated: false
        schema:
          type: string
        style: simple
        explode: false
      - name: _preview
        in: query
        description: Enables preview mode (requires a valid bearer JWT token)
        required: false
        deprecated: false
        schema:
          type: boolean
        style: form
        explode: false
        example: '1'
      security:
      - JWT: []
components:
  schemas:
    HydraCollectionBaseSchemaNoPagination:
      type: object
      properties:
        hydra:totalItems:
          type: integer
          minimum: 0
        hydra:search:
          type: object
          properties:
            '@type':
              type: string
            hydra:template:
              type: string
            hydra:variableRepresentation:
              type: string
            hydra:mapping:
              type: array
              items:
                type: object
                properties:
                  '@type':
                    type: string
                  variable:
                    type: string
                  property:
                    type:
                    - string
                    - 'null'
                  required:
                    type: boolean
    HydraItemBaseSchema:
      type: object
      properties:
        '@context':
          oneOf:
          - type: string
          - type: object
            properties:
              '@vocab':
                type: string
              hydra:
                type: string
                enum:
                - http://www.w3.org/ns/hydra/core#
            required:
            - '@vocab'
            - hydra
            additionalProperties: true
        '@id':
          type: string
        '@type':
          type: string
      required:
      - '@id'
      - '@type'
    Folder.x-www-form-urlencoded-folder:
      type: object
      description: Folders entity represent a directory on server with datetime and naming.
      properties:
        color:
          maxLength: 7
          default: '#000000'
          type: string
        slug:
          maxLength: 250
          default: ''
          type: string
        visible:
          default: true
          type: boolean
        locked:
          default: false
          type: boolean
        name:
          readOnly: true
          type:
          - string
          - 'null'
      required:
      - slug
    HydraCollectionBaseSchema:
      allOf:
      - $ref: '#/components/schemas/HydraCollectionBaseSchemaNoPagination'
      - type: object
        properties:
          hydra:view:
            type: object
            properties:
              '@id':
                type: string
                format: iri-reference
              '@type':
                type: string
              hydra:first:
                type: string
                format: iri-reference
              hydra:last:
                type: string
                format: iri-reference
              hydra:previous:
                type: string
                format: iri-reference
              hydra:next:
                type: string
                format: iri-reference
            example:
              '@id': string
              '@type': string
              hydra:first: string
              hydra:last: string
              hydra:previous: string
              hydra:next: string
    Error.jsonld:
      allOf:
      - $ref: '#/components/schemas/HydraItemBaseSchema'
      - type: object
        properties:
          title:
            readOnly: true
            description: A short, human-readable summary of the problem.
            type:
            - string
            - 'null'
          detail:
            readOnly: true
            description: A human-readable explanation specific to this occurrence of the problem.
            type:
            - string
            - 'null'
          status:
            type:
            - number
            - 'null'
            examples:
            - 404
            default: 400
          instance:
            readOnly: true
            description: A URI reference that identifies the specific occurrence of the problem. It may or may not yield further information if dereferenced.
            type:
            - string
            - 'null'
          type:
            readOnly: true
            description: A URI reference that identifies the problem type
            type: string
          description:
            readOnly: true
            type:
            - string
            - 'null'
      description: A representation of common errors.
    Folder-folder:
      type: object
      description: Folders entity represent a directory on server with datetime and naming.
      properties:
        color:
          maxLength: 7
          default: '#000000'
          type: string
        slug:
          maxLength: 250
          default: ''
          type: string
        visible:
          default: true
          type: boolean
        locked:
          default: false
          type: boolean
        name:
          readOnly: true
          type:
          - string
          - 'null'
      required:
      - slug
    Error:
      type: object
      description: A representation of common errors.
      properties:
        title:
          readOnly: true
          description: A short, human-readable summary of the problem.
          type:
          - string
          - 'null'
        detail:
          readOnly: true
          description: A human-readable explanation specific to this occurrence of the problem.
          type:
          - string
          - 'null'
        status:
          type:
          - number
          - 'null'
          examples:
          - 404
          default: 400
        instance:
          readOnly: true
          description: A URI reference that identifies the specific occurrence of the problem. It may or may not yield further information if dereferenced.
          type:
          - string
          - 'null'
        type:
          readOnly: true
          description: A URI reference that identifies the problem type
          type: string
    Folder.jsonld-folder:
      allOf:
      - $ref: '#/components/schemas/HydraItemBaseSchema'
      - type: object
        properties:
          color:
            maxLength: 7
            default: '#000000'
            type: string
          slug:
            maxLength: 250
            default: ''
            type: string
          visible:
            default: true
            type: boolean
          locked:
            default: false
            type: boolean
          name:
            readOnly: true
            type:
            - string
            - 'null'
        required:
        - slug
      description: Folders entity represent a directory on server with datetime and naming.
  securitySchemes:
    JWT:
      type: http
      scheme: bearer
      bearerFormat: JWT
